proyecto_front_homepage:
    pattern:  /{_locale}
    defaults: { _controller: ProyectoFrontBundle:Default:inicio }
    requirements:
        _locale:  es|en|fr|de|ch
proyecto_front_index:
    pattern:  /
    defaults: { _controller: ProyectoFrontBundle:Default:index }

proyecto_front_actualiza_galeria:
    pattern:  /{_locale}/actualiza/galeria
    defaults: { _controller: ProyectoFrontBundle:Default:actualizaGaleria }
    requirements:
      _method: POST
      _locale:  es|en|fr|de|ch
proyecto_front_actualiza_exposiciones:
    pattern:  /{_locale}/actualiza/exposiciones
    defaults: { _controller: ProyectoFrontBundle:Default:actualizaExposiciones }
    requirements:
      _method: POST
      _locale:  es|en|fr|de|ch
proyecto_front_article:
    pattern:  /{_locale}/article/{id}
    defaults: { _controller: ProyectoFrontBundle:Default:article }
    requirements:
        _locale:  es|en|fr|de|ch
proyecto_front_resource:
    pattern:  /{_locale}/{idpage}/{galerianombre}/{idgaleria}/{recursonombre}/{idrecurso}
    defaults: { _controller: ProyectoFrontBundle:Default:resource, idpage: '1' }
    requirements:
        _locale:  es|en|fr|de|ch
proyecto_front_page:
    pattern:  /{_locale}/{id}/{friendlyname}
    defaults: { _controller: ProyectoFrontBundle:Default:page }
    requirements:
        _locale:  es|en|fr|de|ch

proyecto_front_cerrarsesion:
    pattern:  /logout
    defaults: { _controller: ProyectoFrontBundle:Default:inicio }

